# LAB | Extractive Question Answering

This notebook demonstrates how Pinecone helps you build an extractive question-answering application. To build an extractive question-answering system, we need three main components:

- A vector index to store and run semantic search
- A retriever model for embedding context passages
- A reader model to extract answers

We will use the SQuAD dataset, which consists of **questions** and **context** paragraphs containing question **answers**. We generate embeddings for the context passages using the retriever, index them in the vector database, and query with semantic search to retrieve the top k most relevant contexts containing potential answers to our question. We then use the reader model to extract the answers from the returned contexts.

Let's get started by installing the packages needed for notebook to run:

In [29]:
import os

# Ask user to input the API key securely
from getpass import getpass
os.environ["PINECONE_API_KEY"] = getpass("Enter your Pinecone API key: ")

# Access it when needed
pinecone_api_key = os.getenv("PINECONE_API_KEY")

Enter your Pinecone API key: ··········

In [30]:
# import os
# from dotenv import load_dotenv, find_dotenv
# _ = load_dotenv(find_dotenv())

# OPENAI_API_KEY  = os.getenv('OPENAI_API_KEY')
# PINECONE_API_KEY= os.getenv('PINECONE_API_KEY')

# Install Dependencies

In [31]:
!pip install -qU datasets pinecone-client sentence-transformers torch

# Load Dataset

Now let's load the SQUAD dataset from the HuggingFace Model Hub. We load the dataset into a pandas dataframe and filter the title, question, and context columns, and we drop any duplicate context passages.

In [32]:
from datasets import load_dataset

# load the squad dataset into a pandas dataframe
df = load_dataset("squad", split="train").to_pandas()

In [33]:
df.head()

,id,title,context,question,answers
0,5733be284776f41900661182,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",To whom did the Virgin Mary allegedly appear i...,"{'text': ['Saint Bernadette Soubirous'], 'answ..."
1,5733be284776f4190066117f,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is in front of the Notre Dame Main Building?,"{'text': ['a copper statue of Christ'], 'answe..."
2,5733be284776f41900661180,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",The Basilica of the Sacred heart at Notre Dame...,"{'text': ['the Main Building'], 'answer_start'..."
3,5733be284776f41900661181,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is the Grotto at Notre Dame?,{'text': ['a Marian place of prayer and reflec...
4,5733be284776f4190066117e,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What sits on top of the Main Building at Notre...,{'text': ['a golden statue of the Virgin Mary'...

In [34]:
# select only title and context column
df = df[['title', 'context']]
# drop rows containing duplicate context passages
df = df.drop_duplicates(subset='context')
df

,title,context
0,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha..."
5,University_of_Notre_Dame,"As at most other universities, Notre Dame's st..."
10,University_of_Notre_Dame,The university is the major seat of the Congre...
15,University_of_Notre_Dame,The College of Engineering was established in ...
20,University_of_Notre_Dame,All of Notre Dame's undergraduate students are...
...,...,...
87574,Kathmandu,"Institute of Medicine, the central college of ..."
87579,Kathmandu,Football and Cricket are the most popular spor...
87584,Kathmandu,The total length of roads in Nepal is recorded...
87589,Kathmandu,The main international airport serving Kathman...
87594,Kathmandu,"Kathmandu Metropolitan City (KMC), in order to..."

# Initialize Pinecone Index

The Pinecone index stores vector representations of our context passages which we can retrieve using another vector (query vector). We first need to initialize our connection to Pinecone to create our vector index. For this, we need a free [API key]("https://app.pinecone.io/"), and then we initialize the connection like so:

In [35]:
!pip install -qU langchain-pinecone pinecone-notebooks

In [36]:
# import getpass
# import os

# from pinecone import Pinecone, ServerlessSpec

# if not os.getenv("PINECONE_API_KEY"):
#     os.environ["PINECONE_API_KEY"] = getpass.getpass("Enter your Pinecone API key: ")

# # initialize connection to pinecone (get API key at app.pinecone.io)

# pinecone_api_key = os.environ.get("PINECONE_API_KEY")

In [37]:
from pinecone import Pinecone, ServerlessSpec

spec = ServerlessSpec(
    cloud="aws", region="us-east-1"
)

# connect to pinecone environment
pc = Pinecone(
    api_key = pinecone_api_key,
    environment='us-east-1'  # find next to API key in console
)

Now we create a new index called "question-answering" — we can name the index anything we want. We specify the metric type as "cosine" and dimension as 384 because the retriever we use to generate context embeddings is optimized for cosine similarity and outputs 384-dimension vectors.

In [38]:
index_name = "question-answering"

# check if the extractive-question-answering index exists
if index_name not in pc.list_indexes().names():
    # create the index if it does not exist
    pc.create_index(
        name=index_name,
        dimension=384,            # because retriever model outputs 384-dim vectors
        metric="cosine",          # cosine similarity is standard for embeddings
        spec=spec                 # serverless spec defined earlier
    )
# connect to extractive-question-answering index we created
index = pc.Index(index_name)

# Initialize Retriever

Next, we need to initialize our retriever. The retriever will mainly do two things:

- Generate embeddings for all context passages (context vectors/embeddings)
- Generate embeddings for our questions (query vector/embedding)

The retriever will generate embeddings in a way that the questions and context passages containing answers to our questions are nearby in the vector space. We can use cosine similarity to calculate the similarity between the query and context embeddings to find the context passages that contain potential answers to our question.

We will use a SentenceTransformer model named ``multi-qa-MiniLM-L6-cos-v1`` designed for semantic search and trained on 215M (question, answer) pairs from diverse sources as our retriever.

In [39]:
import torch
from sentence_transformers import SentenceTransformer

# set device to GPU if available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# load the retriever model from huggingface model hub
retriever = SentenceTransformer('sentence-transformers/multi-qa-MiniLM-L6-cos-v1', device=device)
retriever

SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

# Generate Embeddings and Upsert

Next, we need to generate embeddings for the context passages. We will do this in batches to help us more quickly generate embeddings and upload them to the Pinecone index. When passing the documents to Pinecone, we need an id (a unique value), context embedding, and metadata for each document representing context passages in the dataset. The metadata is a dictionary containing data relevant to our embeddings, such as the article title, context passage, etc.

In [40]:
from tqdm.auto import tqdm

# we will use batches of 64
batch_size = 64

for i in tqdm(range(0, len(df), batch_size)):
    # find end of batch
    batch_end = min(i + batch_size, len(df))
    # extract batch
    batch = df.iloc[i:batch_end]
    # generate embeddings for batch
    emb = retriever.encode(batch["context"].tolist()).tolist()
    # get metadata
    meta = [{"title": title, "context": context} for title, context in zip(batch["title"], batch["context"])]
    # create unique IDs
    ids = [str(x) for x in range(i, batch_end)]
    # add all to upsert list
    to_upsert = list(zip(ids, emb, meta))
    # upsert/insert these records to pinecone
    _ = index.upsert(vectors=to_upsert)

# check that we have all vectors in index
index.describe_index_stats()

  0%|          | 0/296 [00:00<?, ?it/s]

{'dimension': 384,
 'index_fullness': 0.0,
 'metric': 'cosine',
 'namespaces': {'': {'vector_count': 18816}},
 'total_vector_count': 18816,
 'vector_type': 'dense'}

# Initialize Reader

We use the `deepset/electra-base-squad2` model from the HuggingFace model hub as our reader model. We load this model into a "question-answering" pipeline from HuggingFace transformers and feed it our questions and context passages individually. The model gives a prediction for each context we pass through the pipeline.

In [41]:
from transformers import pipeline

model_name = 'deepset/electra-base-squad2'
# load the reader model into a question-answering pipeline
reader = pipeline(tokenizer=model_name, model=model_name, task='question-answering', device=device)
reader

Device set to use cuda

Now all the components we need are ready. Let's write some helper functions to execute our queries. The `get_context` function retrieves the context embeddings containing answers to our question from the Pinecone index, and the `extract_answer` function extracts the answers from these context passages.

In [42]:
# gets context passages from the pinecone index
def get_context(question, top_k):
    # generate embeddings for the question
    xq = retriever.encode([question]).tolist()
    # search pinecone index for context passage with the answer
    xc = index.query(vector=xq[0], top_k=top_k, include_metadata=True)
    # extract the context passage from pinecone search result
    c = [match['metadata']['context'] for match in xc['matches']]
    return c

In [43]:
from pprint import pprint

# extracts answer from the context passage
def extract_answer(question, context):
    results = []
    for c in context:
        # feed the reader the question and contexts to extract answers
        answer = reader(question=question, context=c)
        # add the context to answer dict for printing both together
        answer["context"] = c
        results.append(answer)
    # sort the result based on the score from reader model
    sorted_result = pprint(sorted(results, key=lambda x: x['score'], reverse=True))
    return sorted_result

In [44]:
question = "How much oil is Egypt producing in a day?"
context = get_context(question, top_k = 1)
context

['Egypt was producing 691,000 bbl/d of oil and 2,141.05 Tcf of natural gas (in 2013), which makes Egypt as the largest oil producer not member of the Organization of the Petroleum Exporting Countries (OPEC) and the second-largest dry natural gas producer in Africa. In 2013, Egypt was the largest consumer of oil and natural gas in Africa, as more than 20% of total oil consumption and more than 40% of total dry natural gas consumption in Africa. Also, Egypt possesses the largest oil refinery capacity in Africa 726,000 bbl/d (in 2012). Egypt is currently planning to build its first nuclear power plant in El Dabaa city, northern Egypt.']

As we can see, the retiever is working fine and gets us the context passage that contains the answer to our question. Now let's use the reader to extract the exact answer from the context passage.

In [45]:
extract_answer(question, context)

[{'answer': '691,000 bbl/d',
  'context': 'Egypt was producing 691,000 bbl/d of oil and 2,141.05 Tcf of '
             'natural gas (in 2013), which makes Egypt as the largest oil '
             'producer not member of the Organization of the Petroleum '
             'Exporting Countries (OPEC) and the second-largest dry natural '
             'gas producer in Africa. In 2013, Egypt was the largest consumer '
             'of oil and natural gas in Africa, as more than 20% of total oil '
             'consumption and more than 40% of total dry natural gas '
             'consumption in Africa. Also, Egypt possesses the largest oil '
             'refinery capacity in Africa 726,000 bbl/d (in 2012). Egypt is '
             'currently planning to build its first nuclear power plant in El '
             'Dabaa city, northern Egypt.',
  'end': 33,
  'score': 0.9999855201993455,
  'start': 20}]

The reader model predicted with 99% accuracy the correct answer *691,000 bbl/d* as seen from the context passage. Let's run few more queries.

In [46]:
question = "What are the first names of the men that invented youtube?"
context = get_context(question, top_k=1)
extract_answer(question, context)

[{'answer': 'Hurley and Chen',
  'context': 'According to a story that has often been repeated in the media, '
             'Hurley and Chen developed the idea for YouTube during the early '
             'months of 2005, after they had experienced difficulty sharing '
             "videos that had been shot at a dinner party at Chen's apartment "
             'in San Francisco. Karim did not attend the party and denied that '
             'it had occurred, but Chen commented that the idea that YouTube '
             'was founded after a dinner party "was probably very strengthened '
             'by marketing ideas around creating a story that was very '
             'digestible".',
  'end': 79,
  'score': 0.9999276399612427,
  'start': 64}]

In [47]:
question = "What is Albert Eistein famous for?"
context = get_context(question, top_k=1)
extract_answer(question, context)

[{'answer': 'his theories of special relativity and general relativity',
  'context': 'Albert Einstein is known for his theories of special relativity '
             'and general relativity. He also made important contributions to '
             'statistical mechanics, especially his mathematical treatment of '
             'Brownian motion, his resolution of the paradox of specific '
             'heats, and his connection of fluctuations and dissipation. '
             'Despite his reservations about its interpretation, Einstein also '
             'made contributions to quantum mechanics and, indirectly, quantum '
             'field theory, primarily through his theoretical studies of the '
             'photon.',
  'end': 86,
  'score': 0.9500371217727661,
  'start': 29}]

Let's run another question. This time for top 3 context passages from the retriever.

In [48]:
question = "Who was the first person to step foot on the moon?"
context = get_context(question, top_k=3)
extract_answer(question, context)

[{'answer': 'Armstrong',
  'context': 'The trip to the Moon took just over three days. After achieving '
             'orbit, Armstrong and Aldrin transferred into the Lunar Module, '
             'named Eagle, and after a landing gear inspection by Collins '
             'remaining in the Command/Service Module Columbia, began their '
             'descent. After overcoming several computer overload alarms '
             'caused by an antenna switch left in the wrong position, and a '
             'slight downrange error, Armstrong took over manual flight '
             'control at about 180 meters (590 ft), and guided the Lunar '
             'Module to a safe landing spot at 20:18:04 UTC, July 20, 1969 '
             '(3:17:04 pm CDT). The first humans on the Moon would wait '
             'another six hours before they ventured out of their craft. At '
             '02:56 UTC, July 21 (9:56 pm CDT July 20), Armstrong became the '
             'first human to set foot on the Moon.',
  'end': 80,
  'score': 0.9998037815093994,
  'start': 71},
 {'answer': 'Aldrin',
  'context': 'The first step was witnessed by at least one-fifth of the '
             'population of Earth, or about 723 million people. His first '
             "words when he stepped off the LM's landing footpad were, "
             '"That\'s one small step for [a] man, one giant leap for '
             'mankind." Aldrin joined him on the surface almost 20 minutes '
             'later. Altogether, they spent just under two and one-quarter '
             'hours outside their craft. The next day, they performed the '
             'first launch from another celestial body, and rendezvoused back '
             'with Columbia.',
  'end': 246,
  'score': 0.7011048772837967,
  'start': 240},
 {'answer': 'Frank Borman',
  'context': 'On December 21, 1968, Frank Borman, James Lovell, and William '
             'Anders became the first humans to ride the Saturn V rocket into '
             'space on Apollo 8. They also became the first to leave low-Earth '
             'orbit and go to another celestial body, and entered lunar orbit '
             'on December 24. They made ten orbits in twenty hours, and '
             'transmitted one of the most watched TV broadcasts in history, '
             'with their Christmas Eve program from lunar orbit, that '
             'concluded with a reading from the biblical Book of Genesis. Two '
             'and a half hours after the broadcast, they fired their engine to '
             'perform the first trans-Earth injection to leave lunar orbit and '
             'return to the Earth. Apollo 8 safely landed in the Pacific ocean '
             "on December 27, in NASA's first dawn splashdown and recovery.",
  'end': 34,
  'score': 0.5020967973396182,
  'start': 22}]

The result looks pretty good.

In [49]:
# pc.delete_index(index_name)

### Add a few more questions. What did you observe?

In [53]:
question = "What is the best month to plant tomatos"
context = get_context(question, top_k=3)
extract_answer(question, context)

[{'answer': 'autumn',
  'context': 'During the summer growing season, phosphate is at a high level. '
             'It has a vital role in the breakdown of the sugars manufactured '
             'by chlorophyll. But in the fall, phosphate, along with the other '
             'chemicals and nutrients, moves out of the leaf into the stem of '
             'the plant. When this happens, the sugar-breakdown process '
             'changes, leading to the production of anthocyanin pigments. The '
             'brighter the light during this period, the greater the '
             'production of anthocyanins and the more brilliant the resulting '
             'color display. When the days of autumn are bright and cool, and '
             'the nights are chilly but not freezing, the brightest '
             'colorations usually develop.',
  'end': 536,
  'score': 0.0035211259964853525,
  'start': 530},
 {'answer': 'April is the driest month',
  'context': 'Like much of the southeastern United States, Raleigh has a humid '
             'subtropical climate (Köppen Cfa), with four distinct seasons. '
             'Winters are short and generally cool, with a January daily '
             'average of 41.0 °F (5.0 °C). On average, there are 69 nights per '
             'year that drop to or below freezing, and only 2.7 days that fail '
             'to rise above freezing. April is the driest month, with an '
             'average of 2.91 inches (73.9 mm) of precipitation. Precipitation '
             'is well distributed around the year, with a slight maximum '
             'between July and September; on average, July is the wettest '
             'month, owing to generally frequent, sometimes heavy, showers and '
             'thunderstorms. Summers are hot and humid, with a daily average '
             'in July of 80.0 °F (26.7 °C). There are 48 days per year with '
             'highs at or above 90 °F (32 °C). Autumn is similar to spring '
             'overall but has fewer days of rainfall. Extremes in temperature '
             'have ranged from −9 °F (−23 °C) on January 21, 1985 up to 105 °F '
             '(41 °C), most recently on July 8, 2012.',
  'end': 365,
  'score': 9.755302698977175e-08,
  'start': 340},
 {'answer': 'dry periods',
  'context': 'The central Sahara is estimated to include five hundred species '
             'of plants, which is extremely low considering the huge extent of '
             'the area. Plants such as acacia trees, palms, succulents, spiny '
             'shrubs, and grasses have adapted to the arid conditions, by '
             'growing lower to avoid water loss by strong winds, by storing '
             'water in their thick stems to use it in dry periods, by having '
             'long roots that travel horizontally to reach the maximum area of '
             'water and to find any surface moisture and by having small thick '
             'leaves or needles to prevent water loss by evapo-transpiration. '
             'Plant leaves may dry out totally and then recover.',
  'end': 366,
  'score': 5.0808120731493656e-12,
  'start': 355}]

In [54]:
question = "Who is the strongest person on earth?"
context = get_context(question, top_k=3)
extract_answer(question, context)

[{'answer': 'Samichlaus',
  'context': ' The strength of beers has climbed during the later years of the '
             '20th century. Vetter 33, a 10.5% abv (33 degrees Plato, hence '
             'Vetter "33") doppelbock, was listed in the 1994 Guinness Book of '
             'World Records as the strongest beer at that time, though '
             'Samichlaus, by the Swiss brewer Hürlimann, had also been listed '
             'by the Guinness Book of World Records as the strongest at 14% '
             'abv. Since then, some brewers have used champagne yeasts to '
             'increase the alcohol content of their beers. Samuel Adams '
             'reached 20% abv with Millennium, and then surpassed that amount '
             'to 25.6% abv with Utopias. The strongest beer brewed in Britain '
             "was Baz's Super Brew by Parish Brewery, a 23% abv beer. In "
             'September 2011, the Scottish brewery BrewDog produced Ghost '
             "Deer, which, at 28%, they claim to be the world's strongest beer "
             'produced by fermentation alone.',
  'end': 259,
  'score': 0.8802436406185734,
  'start': 249},
 {'answer': 'von Neumann',
  'context': '"I have sometimes wondered whether a brain like von Neumann\'s '
             'does not indicate a species superior to that of man", said Nobel '
             'Laureate Hans Bethe of Cornell University. "It seems fair to say '
             'that if the influence of a scientist is interpreted broadly '
             'enough to include impact on fields beyond science proper, then '
             'John von Neumann was probably the most influential mathematician '
             'who ever lived," wrote Miklós Rédei in "Selected Letters." James '
             'Glimm wrote: "he is regarded as one of the giants of modern '
             'mathematics". The mathematician Jean Dieudonné called von '
             'Neumann "the last of the great mathematicians", while Peter Lax '
             'described him as possessing the "most scintillating intellect of '
             'this century".',
  'end': 59,
  'score': 9.510275596549822e-13,
  'start': 48},
 {'answer': 'influential',
  'context': 'West is one of the best-selling artists of all time, having sold '
             'more than 32 million albums and 100 million digital downloads '
             'worldwide. He has won a total of 21 Grammy Awards, making him '
             'one of the most awarded artists of all time and the most '
             'Grammy-awarded artist of his age. Three of his albums rank on '
             'Rolling Stone\'s 2012 "500 Greatest Albums of All Time" list; '
             'two of his albums feature at first and eighth, respectively, in '
             "Pitchfork Media's The 100 Best Albums of 2010–2014. He has also "
             'been included in a number of Forbes annual lists. Time named him '
             'one of the 100 most influential people in the world in 2005 and '
             '2015.',
  'end': 593,
  'score': 7.41703519348963e-14,
  'start': 582}]

In [55]:
question = "Who was the first person to fly accross the atlantic ocean?"
context = get_context(question, top_k=3)
extract_answer(question, context)

[{'answer': 'A Stinson Detroiter',
  'context': 'After several failed attempts, in 1930 the first aeroplane '
             'reached Bermuda. A Stinson Detroiter seaplane flying from New '
             'York, it had to land twice in the ocean: once because of '
             'darkness and again to refuel. Navigation and weather forecasting '
             'improved in 1933 when the Royal Air Force (then responsible for '
             "providing equipment and personnel for the Royal Navy's Fleet Air "
             'Arm) established a station at the Royal Naval Dockyard to repair '
             '(and supply replacement) float planes for the fleet. In 1936 '
             'Luft Hansa began to experiment with seaplane flights from Berlin '
             'via the Azores with continuation to New York City.',
  'end': 95,
  'score': 0.6580695185693912,
  'start': 76},
 {'answer': 'Juan de Bermúdez',
  'context': 'The first known European explorer to reach Bermuda was Spanish '
             'sea captain Juan de Bermúdez in 1503, after whom the islands are '
             'named. He claimed the apparently uninhabited islands for the '
             'Spanish Empire. Paying two visits to the archipelago, Bermúdez '
             'never landed on the islands, but did create a recognisable map '
             'of the archipelago. Shipwrecked Portuguese mariners are now '
             'thought to have been responsible for the 1543 inscription in '
             'Portuguese Rock (previously called Spanish Rock). Subsequent '
             'Spanish or other European parties are believed to have released '
             'pigs there, which had become feral and abundant on the island by '
             'the time European settlement began. In 1609, the English '
             'Virginia Company, which had established Jamestown in Virginia (a '
             'term originally applied to all of the North American continent) '
             'two years earlier, permanently settled Bermuda in the aftermath '
             'of a hurricane, when the crew and passengers of the Sea Venture '
             'steered the ship onto the surrounding reef to prevent its '
             'sinking, then landed ashore.',
  'end': 91,
  'score': 2.105250774598645e-12,
  'start': 75},
 {'answer': 'Antarctic Circle',
  'context': 'European maps continued to show this hypothesized land until '
             "Captain James Cook's ships, HMS Resolution and Adventure, "
             'crossed the Antarctic Circle on 17 January 1773, in December '
             '1773 and again in January 1774. Cook came within about 120 km '
             '(75 mi) of the Antarctic coast before retreating in the face of '
             'field ice in January 1773. The first confirmed sighting of '
             'Antarctica can be narrowed down to the crews of ships captained '
             'by three individuals. According to various organizations (the '
             'National Science Foundation, NASA, the University of California, '
             'San Diego, and other sources), ships captained by three men '
             'sighted Antarctica or its ice shelf in 1820: von Bellingshausen '
             '(a captain in the Imperial Russian Navy), Edward Bransfield (a '
             'captain in the Royal Navy), and Nathaniel Palmer (a sealer out '
             'of Stonington, Connecticut). The expedition led by von '
             'Bellingshausen and Lazarev on the ships Vostok and Mirny reached '
             "a point within 32 km (20 mi) from Queen Maud's Land and recorded "
             'the sight of an ice shelf at 69°21′28″S 2°14′50″W\ufeff / '
             '\ufeff69.35778°S 2.24722°W\ufeff / -69.35778; -2.24722, which '
             'became known as the Fimbul ice shelf. This happened three days '
             'before Bransfield sighted land, and ten months before Palmer did '
             'so in November 1820. The first documented landing on Antarctica '
             'was by the American sealer John Davis, apparently at Hughes Bay, '
             'near Cape Charles, in West Antarctica on 7 February 1821, '
             'although some historians dispute this claim. The first recorded '
             'and confirmed landing was at Cape Adair in 1895.',
  'end': 147,
  'score': 1.2561127268537198e-13,
  'start': 131}]